name: Update
on:
  schedule:
    - cron: "0 */1 * * *"
  
jobs:
  update-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup python
        uses: actions/setup-python3@v4.5.0
        with:
          python-version: 3.11.1
        
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Update token list
        run: python3 main.py
