name: Update
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  update-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check repo
        uses: actions/checkout@v3
        
      - name: Setup python
        uses: actions/setup-python3@v4
        with:
          python-version: "3.11"
        
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Update token list
        run: python3 main.py
